package csi.vidaplus.rcm.dataimport.model;

import java.util.Date;
import java.util.List;

import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.annotations.ApiModelProperty;

@Document(collection = "encounter")
public class Encounter extends BaseModel {

	@ApiModelProperty("A unique value generated by RCM system for the hospital when registered")
	private String hospitalGroupId;

	private String encounterId;
	private String referenceEncounterId;
	@ApiModelProperty("Invoice generated date")
	private Date invoiceDateTime;
	
	private Patient patient;
	
	@ApiModelProperty(value = "System id of the company")
	private String companyId;
	@ApiModelProperty(value = "RCM system defined id for payer")
	private String payerId;
	private String policyType;
	private String policyNumber;
	private Double companyShare;

	@ApiModelProperty(value = "Clinic id of the RCM system")
	private String clinicId;
	@ApiModelProperty(value = "Doctor id id of the RCM system")
	private String doctorId;
	@ApiModelProperty(value = "Id of the location where the Encounter took place,this should be defined in the RCM system")
	private String facilityId;

	@ApiModelProperty(value = "The predominant speciality of the primary caregiver for the Encounter,value should be defined in the RCM system", example = "Urology,Cardiology")
	private String specialityId;
	private String transferedFromFacilityId;//
	private String transferedToFacilityId;
	@ApiModelProperty("The total amount of the encounter")
	private Double grossAmount;
	@ApiModelProperty("The total amount of the encounter")
	private Double netAmount;
	private Double patientShare;
	private Boolean patientPaid;

	private String visitType;
	private String department;
	private String chiefComplaint;
	private String significant;
	private String otherConditionsDiagnosis;
	private String pregnancyLMP;
	private String estimatedLengthOfStay;
	private String expectedDateOfAdmission;
	private String bloodPressure;
	private String pulse;
	private String temperature;

	private String approvalNo;
	private String encounterType;
	private String encounterStartType;
	private String encounterEndType;

	private Date serviceStartTime;
	private Date serviceEndTime;

	@ApiModelProperty(value = "The information about the family relationships under the same Payer", allowableValues = "Principal,Spouse,Child,Parent,Other")
	private String memberRelation; // - Principal,Spouse,Child,Parent,Other

	@ApiModelProperty("If the reported member has no other related family members under the same Payer, (MemberRelation = Principal) then the MemberRelationTo value should be the same as Member.")
	private String memberRelationTo;
	private String remarks;

	@Transient
	private List<EncounterDiagnosis> encounterDiagnosis;
	
	@Transient
	private List<EncounterInvoice> encounterInvoices;
	
	@Transient
	private List<DoctorNotes> doctorNotes;
	
	@Transient
	private List<NurseNotes> nurseNotes;

	public String getHospitalGroupId() {
		return hospitalGroupId;
	}

	public void setHospitalGroupId(String hospitalGroupId) {
		this.hospitalGroupId = hospitalGroupId;
	}

	public String getEncounterId() {
		return encounterId;
	}

	public void setEncounterId(String encounterId) {
		this.encounterId = encounterId;
	}

	public String getReferenceEncounterId() {
		return referenceEncounterId;
	}

	public void setReferenceEncounterId(String referenceEncounterId) {
		this.referenceEncounterId = referenceEncounterId;
	}

	public Date getInvoiceDateTime() {
		return invoiceDateTime;
	}

	public void setInvoiceDateTime(Date invoiceDateTime) {
		this.invoiceDateTime = invoiceDateTime;
	}
	
	public Patient getPatient() {
		return patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getPayerId() {
		return payerId;
	}

	public void setPayerId(String payerId) {
		this.payerId = payerId;
	}

	public Double getCompanyShare() {
		return companyShare;
	}

	public void setCompanyShare(Double companyShare) {
		this.companyShare = companyShare;
	}

	public String getClinicId() {
		return clinicId;
	}

	public void setClinicId(String clinicId) {
		this.clinicId = clinicId;
	}

	public String getDoctorId() {
		return doctorId;
	}

	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId;
	}

	public String getFacilityId() {
		return facilityId;
	}

	public void setFacilityId(String facilityId) {
		this.facilityId = facilityId;
	}

	public String getSpecialityId() {
		return specialityId;
	}

	public void setSpecialityId(String specialityId) {
		this.specialityId = specialityId;
	}

	public String getTransferedFromFacilityId() {
		return transferedFromFacilityId;
	}

	public void setTransferedFromFacilityId(String transferedFromFacilityId) {
		this.transferedFromFacilityId = transferedFromFacilityId;
	}

	public String getTransferedToFacilityId() {
		return transferedToFacilityId;
	}

	public void setTransferedToFacilityId(String transferedToFacilityId) {
		this.transferedToFacilityId = transferedToFacilityId;
	}

	public Double getGrossAmount() {
		return grossAmount;
	}

	public void setGrossAmount(Double grossAmount) {
		this.grossAmount = grossAmount;
	}

	public Double getNetAmount() {
		return netAmount;
	}

	public void setNetAmount(Double netAmount) {
		this.netAmount = netAmount;
	}

	public Double getPatientShare() {
		return patientShare;
	}

	public void setPatientShare(Double patientShare) {
		this.patientShare = patientShare;
	}

	public Boolean getPatientPaid() {
		return patientPaid;
	}

	public void setPatientPaid(Boolean patientPaid) {
		this.patientPaid = patientPaid;
	}

	public String getVisitType() {
		return visitType;
	}

	public void setVisitType(String visitType) {
		this.visitType = visitType;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getChiefComplaint() {
		return chiefComplaint;
	}

	public void setChiefComplaint(String chiefComplaint) {
		this.chiefComplaint = chiefComplaint;
	}

	public String getSignificant() {
		return significant;
	}

	public void setSignificant(String significant) {
		this.significant = significant;
	}

	public String getOtherConditionsDiagnosis() {
		return otherConditionsDiagnosis;
	}

	public void setOtherConditionsDiagnosis(String otherConditionsDiagnosis) {
		this.otherConditionsDiagnosis = otherConditionsDiagnosis;
	}

	public String getPregnancyLMP() {
		return pregnancyLMP;
	}

	public void setPregnancyLMP(String pregnancyLMP) {
		this.pregnancyLMP = pregnancyLMP;
	}

	public String getEstimatedLengthOfStay() {
		return estimatedLengthOfStay;
	}

	public void setEstimatedLengthOfStay(String estimatedLengthOfStay) {
		this.estimatedLengthOfStay = estimatedLengthOfStay;
	}

	public String getExpectedDateOfAdmission() {
		return expectedDateOfAdmission;
	}

	public void setExpectedDateOfAdmission(String expectedDateOfAdmission) {
		this.expectedDateOfAdmission = expectedDateOfAdmission;
	}

	public String getBloodPressure() {
		return bloodPressure;
	}

	public void setBloodPressure(String bloodPressure) {
		this.bloodPressure = bloodPressure;
	}

	public String getPulse() {
		return pulse;
	}

	public void setPulse(String pulse) {
		this.pulse = pulse;
	}

	public String getTemperature() {
		return temperature;
	}

	public void setTemperature(String temperature) {
		this.temperature = temperature;
	}

	public String getApprovalNo() {
		return approvalNo;
	}

	public void setApprovalNo(String approvalNo) {
		this.approvalNo = approvalNo;
	}

	public String getEncounterType() {
		return encounterType;
	}

	public void setEncounterType(String encounterType) {
		this.encounterType = encounterType;
	}

	public String getEncounterStartType() {
		return encounterStartType;
	}

	public void setEncounterStartType(String encounterStartType) {
		this.encounterStartType = encounterStartType;
	}

	public String getEncounterEndType() {
		return encounterEndType;
	}

	public void setEncounterEndType(String encounterEndType) {
		this.encounterEndType = encounterEndType;
	}

	public Date getServiceStartTime() {
		return serviceStartTime;
	}

	public void setServiceStartTime(Date serviceStartTime) {
		this.serviceStartTime = serviceStartTime;
	}

	public Date getServiceEndTime() {
		return serviceEndTime;
	}

	public void setServiceEndTime(Date serviceEndTime) {
		this.serviceEndTime = serviceEndTime;
	}


	public String getMemberRelation() {
		return memberRelation;
	}

	public void setMemberRelation(String memberRelation) {
		this.memberRelation = memberRelation;
	}

	public String getMemberRelationTo() {
		return memberRelationTo;
	}

	public void setMemberRelationTo(String memberRelationTo) {
		this.memberRelationTo = memberRelationTo;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public List<EncounterDiagnosis> getEncounterDiagnosis() {
		return encounterDiagnosis;
	}

	public void setEncounterDiagnosis(List<EncounterDiagnosis> encounterDiagnosis) {
		this.encounterDiagnosis = encounterDiagnosis;
	}

	public String getPolicyType() {
		return policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

	public String getPolicyNumber() {
		return policyNumber;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public List<EncounterInvoice> getEncounterInvoices() {
		return encounterInvoices;
	}

	public void setEncounterInvoices(List<EncounterInvoice> encounterInvoices) {
		this.encounterInvoices = encounterInvoices;
	}

	public List<DoctorNotes> getDoctorNotes() {
		return doctorNotes;
	}

	public void setDoctorNotes(List<DoctorNotes> doctorNotes) {
		this.doctorNotes = doctorNotes;
	}

	public List<NurseNotes> getNurseNotes() {
		return nurseNotes;
	}

	public void setNurseNotes(List<NurseNotes> nurseNotes) {
		this.nurseNotes = nurseNotes;
	}

	
}
