spring:
  datasource:
    url: jdbc:sqlserver://10.50.100.185:1433;databaseName=HISGENX
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: hmgdbuser
    password: 123456
    platform: mssql
  jpa:
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate.ddl-auto: validate

#Server config
server:
   port: 10025