# See http://masterData.spring.io/spring-boot/masterData/current/reference/html/common-application-properties.html

spring:
  thymeleaf.cache: false
  main.show-banner: false
  #Mongo Config
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.database: csi_rcm_data_dictionary
    #mongodb.repositories.enabled: true
  jackson:
       date-format: yyyy-MM-dd HH:mm:ss

debug: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.Query: DEBUG

#Server config
server:
  port: 8096
  contextPath: /datadictionary
#eureka:
#client:
  #serviceUrl:
      #defaultZone: http://localhost:8761/eureka/

#Swagger config
swagger:
  title: CSI RCM Data Dictionary Manager
  description: This is the API of Data Dictionary Service
  licnesne: CSI Licence 1.0














