#Server config
server:
  port: 10012
  contextPath: /widget
eureka:
client:
  serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Swagger config
swagger:
  title: CSI RCM Master Data Manager
  description: This is the API of Master Data Service
  licnesne: CSI Licence 1.0