spring:
  application:
    name: csi-rcm-minimum-data-validation
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rcm
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active:
    - prod
server:
  port: 7778
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
rcm-claims-data-import:
  ribbon:
    ActiveConnectionsLimit: 10    
    ServerListRefreshInterval: 5000
logging:
  file: datavalidation.log
debug: true

  
  