spring:
  profiles:
    active:
    - qa
  thymeleaf.cache: false
  main.show-banner: false
  #Mongo Config
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.database: csi_rcm_master_data
    #mongodb.repositories.enabled: true
  jackson:
       date-format: yyyy-MM-dd HH:mm:ss

debug: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.Query: DEBUG

#Server config
server:
  port: 10003
  contextPath: /masterdata
eureka:
client:
  serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Swagger config
swagger:
  title: CSI RCM Master Data Manager
  description: This is the API of Master Data Service
  licnesne: CSI Licence 1.0